[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'self' *"
    X-Frame-Options = "ALLOWALL"
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18"
